### ISSUE TITLE
一直在关注，能不能给我们也参与进来学习学习，毕竟一个人改那么多端也太累了...接下来有什么计划呀？

### ISSUE THREAD

**Issue by LDmin** [SolidZORO/leaa#17]

**Comment by SolidZORO** [comment]
目前没有特别多的计划，因为手头还有一些别的项目要忙。

实际上我最开始想做的就是一套商城，包括小程序和 App 端什么的，不过光靠自己想怎么做还是蛮难的，还是要有业务场景，然而有业务场景之后 ，又很难做到通用。所以业务场景还不能是一个，而是要想至少两个以上的业务场景。


所以呢，我一个都没想，其实也是比较懒，可能人多一些讨论会好点。考虑是不是弄个群组织什么的。嗯…… 让我好好想想。
