### ISSUE TITLE
Nihao, API is down, cannot test any url. Please check?

### ISSUE THREAD

**Issue by 7sxzx** [SolidZORO/leaa#4]
https://test-leaa-api.herokuapp.com/

**Comment by SolidZORO** [comment]
😂 `heroku` quota is used up, waiting for the next month to take effect.

because of my mistakes, keep 3 repos online at the same time. Later, after I found out the problem, I deployed `www` and `dashboard` to `now.sh`, and the api should not exceed the quota next month.
