### ISSUE TITLE
感觉很厉害，让我燃起了自己做一套东西的小火苗

### ISSUE THREAD

**Issue by johnny19941216** [SolidZORO/leaa#6]
看了一眼博客，很久没更新了啊

**Comment by SolidZORO** [comment]
blog? 你说的是这个 repo 的 DEVLOG 嘛？最近其实也有在写，而且用上了 antd 4 alpha，bug 蛮多 爬坑没爬完就无心写 LOG 了。到时候把 test branch 的坑填完了会 merge 到 master 的。还好早点用上 antd4，新的 <Form /> 实在是好用，终于可以很方便的高内聚，低耦合了，也使得所有前端项目可以完全 hooks 化了，不过，这也意味着之前的所有 <Form /> 都要改，还好插入时间早，改得不算多。

**Comment by redblue9771** [comment]
是真的坑，光next就坑，加上antd，graphql，还不用ts更坑！不过我想问你怎么一天都在commit的 @SolidZORO

**Comment by SolidZORO** [comment]
@redblue9771 因为不想工作只想写代码，写代码的时候又总是觉得这样的代码不是最佳实践，就因为不是公司代码，可以无限期反复打磨，所以会不停的 commit。现在的生活就是每天荒野爬山 + Coding 到深夜。哈哈哈哈哈，自己太菜先拿这个项目练练手。

今天天气不错，又是美好的一天。

![image](https://user-images.githubusercontent.com/661587/70683215-6ae50c00-1cdc-11ea-9c79-e0bacf49f961.png)

**Comment by redblue9771** [comment]
@redblue9771 我柠檬酸了，我还有另外一个坑是用 Windows.

**Comment by redblue9771** [comment]
@SolidZORO 这种生活我柠檬酸了，我还有另外一个坑是用 Windows 🤔.

**Comment by johnny19941216** [comment]
> blog? 你说的是这个 repo 的 DEVLOG 嘛？最近其实也有在写，而且用上了 antd 4 alpha，bug 蛮多，爬坑没爬完就无心写 LOG 了。到时候把 test branch 的坑填完了会 merge 到 master 的。还好早点用上 antd4，新的
> 
> 实在是好用，终于可以很方便的「高内聚，低耦合」了，所有校验的代码都写在 Form 里面就好，而且新的 From 也让所有前端项目可以完全 hooks 化了，不过，这也意味着之前的所有 都要改，还好插入时间早，改得不算多。
😄其实就是想看看一看你的[博客](https://solidzoro.com/)，比如技术什么的，或者分享生活，觉得自己的生活状态实在有点差劲，就想看看别人是怎么生活的

**Comment by SolidZORO** [comment]
@johnny19941216 哈哈原来这样，⛽️加油咯，好的生活都是自己创造出来的。

**Comment by LDmin** [comment]
特别厉害 一个人能搞起这么庞大完整的项目

**Comment by SolidZORO** [comment]
> 特别厉害 一个人能搞起这么庞大完整的项目

就闲暇时段写写没什么啦，最近在开分支转 restful，文件太多转的好头大hhhhh

**Comment by wyudong** [comment]
@SolidZORO 为什么要转 restful，要 graphql 和 restful 都支持吗

**Comment by SolidZORO** [comment]
@wyudong 主要是 Gql 用到后面感觉很麻烦，后端 API 那边麻烦，前端 Dashboard 这边也麻烦。

API 麻烦在权限的处理，以及 req.heads 很多东西需要 trans 到 Gql 的 ctx 里面比较麻烦，需要手动传一些东西，然后就是权限判断，用了 graphql-shield 那套，感觉不够可靠，以及递归查询目前 Gql 还无解，比如无限分类，我不知道要写几层（兼容方案是查出来然后用 JSON.stringify 包一下丢出来一个 string，Dashboard 拿到解），还有就是 GET 的缓存问题，搞也能搞但非常麻烦。以及 entry 和 service 申明要多写一次显得乱糟糟，而且部分语法还是得用 Gql 的 Schema……

Dashboard 麻烦在于一堆 Apollo 的 libs，至少 5 个+，比如 link，cache，http 这些，而且更新频繁，BC 是家常便饭，有时候写着写着更新一下版本就大面积不可用了，而且 throw 没有很好的最佳实践，一些 data 或 error 无法很好的控制。

算了算了不写了，越写感觉 Gql 缺点越多。然后换回 restful，API 的问题都不见了，Dashboard 也只用一个 axios 搞定一切。

说实话，Gql 如果想学习，用还是可以用的，起码是个新技术，但是未来会不会流行，我觉得大概率不会，要火早火了。

这次选型 Gql，然后转 restful 的经验对我未来技术选型还是很关键的，经过这次可能我不再会用面世 < 5ys  的技术。

**Comment by LDmin** [comment]
想知道www的项目放哪了？

**Comment by SolidZORO** [comment]
@LDmin 拆了还没安排，最后版本暂时看这里 https://github.com/SolidZORO/leaa/tree/e3b77b363c8b2214072d5f617b0670499faa4afb/packages/leaa-www

**Comment by LyunKi** [comment]
我用的跟你极度类似的技术栈，taro,ts,antd,graphql,expo,nest,monorepo,结果在搜索monorepo相关的内容的时候看了你的dev log,一不小心就看完了2333.graphql确实不少坑，不过自己写着玩，就想用最新最炫酷的23333
