### ISSUE TITLE
Is it ok to open PR adding Spanish/es-ES locale?

### ISSUE THREAD

**Issue by agustif** [SolidZORO/leaa#7]
I've it working in local, would love to contribute but not sure if welcome or any CONTRIBUTING.md guidelines I should follow.

Thhanks for this awesome project, can't wait for v1.x further development!

**Comment by SolidZORO** [comment]
OK, you can try copy https://github.com/SolidZORO/leaa/tree/master/packages/leaa-dashboard/src/locales/en-US and translate, then give me the PR and leave the rest to me.

**Comment by SolidZORO** [comment]
Hello, recently updated a version, the `api` also supports multiple languages, it seems that adding one more language now is two workloads 😄

api locales in here https://github.com/SolidZORO/leaa/tree/master/packages/leaa-api/src/locales

**Comment by agustif** [comment]
Hey sorry, I started a new job right after wanting to do this, and haven't been able to get much free time for other stuff, might reopen as PR later! Keep up the great project!
