### ISSUE TITLE
关于UserService中的user方法疑惑

### ISSUE THREAD

**Issue by zj-wukewei** [SolidZORO/leaa#8]
你好，这个方法返回了User实体
  // Virtual Field (not in DB)
  @Field(() => [Permission], { nullable: true })
  permissions?: Permission[];
中的permissions为什么在UserResolver的user的Query中能查询到，它不是在Role实体中
 @JoinTable()
  @Field(() => [Role], { nullable: true })
  roles?: Role[];
我也可以看到你在UserService的user方法中有什么特殊的处理

**Comment by SolidZORO** [comment]
Hello, 你可以看看这个文件 https://github.com/SolidZORO/leaa/blob/master/packages/leaa-api/src/modules/user/user.property.ts 我这里用了 ResolveProperty 方法定义 Graphql 的查询。想必可以解决你的疑惑 ：）

**Comment by SolidZORO** [comment]
哈哈，貌似真的写错了。我现在在改 next.js 那边的东西，晚点坚持下，或者你提个 PR 😄

**Comment by SolidZORO** [comment]
修复了，不过感觉 ResolveProperty 上的 type 没什么用，因为我写什么都不影响 graphql，我也疑惑了哈哈哈，放着先回头研究一下为什么。
