### ISSUE TITLE
How can i migrate db?

### ISSUE THREAD

**Issue by kien20011992** [SolidZORO/leaa#9]

**Comment by SolidZORO** [comment]
https://github.com/SolidZORO/leaa/blob/master/packages/leaa-api/README.md

`yarn seed --nuke`

**Comment by kien20011992** [comment]
I mean, when i have any change in database. I need gen a script to migrate db automate
https://typeorm.io/#/migrations/creating-a-new-migration

**Comment by SolidZORO** [comment]
oh, soory, the current version is still adding features and is in the beta stage, so there is no migration.  if you do need to migrate to write a follow typeorm document.

**Comment by kien20011992** [comment]
No problem, i will try to write. Thank you so much
